"""
Django settings for conf project.

Generated by 'django-admin startproject' using Django 5.2.10.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import json
import os
from pathlib import Path

import environ
import ldap
from django_auth_ldap.config import GroupOfNamesType, LDAPGroupQuery, LDAPSearch

# Default values
env = environ.Env(
    # set casting, default value
    ALLOWED_HOSTS_LIST=(list, []),
    AUTH_LDAP_BIND_AS_AUTHENTICATING_USER=(bool, True),
    CSRF_TRUSTED_ORIGINS_LIST=(list, []),
    DEBUG=(bool, False),
    LDAP_TLS_REQUIRE_CERT=(bool, True),
    LDAP_SUPERUSER_GROUP=(str, ""),
    PHONENUMBER_DEFAULT_REGION=(str, "US"),
    PHONENUMBER_DEFAULT_FORMAT=(str, "NATIONAL"),
    TIME_ZONE=(str, "UTC"),
    DJANGO_PRODUCTION=(bool, True),
)

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Take environment variables from .env file
environ.Env.read_env(os.path.join(BASE_DIR, ".env"))

# SECURITY WARNING: don't run with debug turned on in production!
# False if not in os.environ because of casting above
DEBUG = env("DEBUG")

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "handlers": {"console": {"class": "logging.StreamHandler"}},
    "loggers": {
        "django_auth_ldap": {
            # Debug options are listed here: https://docs.python.org/3/library/logging.html#levels
            "level": "DEBUG" if DEBUG else "NOTSET",
            "handlers": ["console"],
        }
    },
}

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env("SECRET_KEY")

ALLOWED_HOSTS = env("ALLOWED_HOSTS_LIST"))
CSRF_TRUSTED_ORIGINS = env("CSRF_TRUSTED_ORIGINS_LIST")

# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    # "dashboard",
    # "phonenumber_field",
    "django_phonedir",
    "simpdir_phonedir",
    "users",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

LOGOUT_REDIRECT_URL = "home"
LOGIN_REDIRECT_URL = "home"

AUTH_USER_MODEL = "users.LDAPuser"

# Keep default Django auth model for per-user permissions and maybe a local superuser.
AUTHENTICATION_BACKENDS = (
    "django_auth_ldap.backend.LDAPBackend",
    # "users.LDAPBackend.CustomLDAPBackend",
    "django.contrib.auth.backends.ModelBackend",
)

ROOT_URLCONF = "conf.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        # "DIRS": [BASE_DIR / "templates", BASE_DIR / "phonedir/templates"],
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "conf.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = env("TIME_ZONE")

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "static/"

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"


# ===================================================
# SETTINGS FOR THIS WEB APP.
LDAP_TLS_REQUIRE_CERT = env("LDAP_TLS_REQUIRE_CERT")
LDAP_BASE_DN = env("LDAP_BASE_DN")
LDAP_GROUP_SEARCH = env("LDAP_GROUP_SEARCH")
LDAP_SUPERUSER_GROUP = env("LDAP_SUPERUSER_GROUP")
LDAP_IS_STAFF = env("LDAP_IS_STAFF")


# ===================================================
# LDAP CONFIGURATION - REQUIRED FOR django_auth_ldap.

# This is what is used to map user attributes from your directory service
# or idenity and access management system.
AUTH_LDAP_USER_ATTR_MAP = {}
with open(
    os.path.join(BASE_DIR, "user-attributes-map.json"), "r"
) as user_attr_map_file:
    AUTH_LDAP_USER_ATTR_MAP = json.load(user_attr_map_file)

AUTH_LDAP_SERVER_URI = env("AUTH_LDAP_SERVER_URI")
AUTH_LDAP_BIND_AS_AUTHENTICATING_USER = env("AUTH_LDAP_BIND_AS_AUTHENTICATING_USER")
AUTH_LDAP_BIND_DN = env("AUTH_LDAP_BIND_DN")
AUTH_LDAP_BIND_PASSWORD = env("AUTH_LDAP_BIND_PASSWORD")

AUTH_LDAP_USER_DN_TEMPLATE = (
    f"{AUTH_LDAP_USER_ATTR_MAP['username']}=%(user)s,{LDAP_BASE_DN}"
)

# Example: Users in this LDAP group gain Django 'is_staff' and 'is_superuser' flags
# LDAP_GROUPS_ADMIN = ["CN=all,OU=Admins,DC=example,DC=com"] # Replace with your actual AD Group DN

AUTH_LDAP_GROUP_SEARCH = LDAPSearch(
    LDAP_GROUP_SEARCH,
    ldap.SCOPE_SUBTREE,
    "(objectClass=top)",
)

AUTH_LDAP_GROUP_TYPE = GroupOfNamesType()
AUTH_LDAP_MIRROR_GROUPS = True

# Simple group restrictions
# AUTH_LDAP_REQUIRE_GROUP = 'cn=enabled,ou=django,ou=groups,dc=example,dc=com'
# AUTH_LDAP_DENY_GROUP = 'cn=disabled,ou=django,ou=groups,dc=example,dc=com'

AUTH_LDAP_USER_FLAGS_BY_GROUP = {
    "is_superuser": LDAP_SUPERUSER_GROUP,
    # The code below needs to be here because "is_staff" is required to log into the Django admin.
    "is_staff": (LDAPGroupQuery(LDAP_IS_STAFF) | LDAPGroupQuery(LDAP_SUPERUSER_GROUP)),
}

# This is the default, but prefer to be explicit.
AUTH_LDAP_ALWAYS_UPDATE_USER = True

# Use LDAP group membership to calculate group permissions.
AUTH_LDAP_FIND_GROUP_PERMS = True

# Cache distinguished names and group memberships for an hour to minimize
# LDAP traffic.
AUTH_LDAP_CACHE_TIMEOUT = 3600

AUTH_LDAP_GLOBAL_OPTIONS = {
    # Warning: OPT_X_TLS_NEVER disables certificate verification.
    ldap.OPT_X_TLS_REQUIRE_CERT: ldap.OPT_X_TLS_DEMAND
    if LDAP_TLS_REQUIRE_CERT
    else ldap.OPT_X_TLS_NEVER
}


# ===================================================
# SETTINGS FOR django-phonenumber-field. --------
PHONENUMBER_DEFAULT_FORMAT = env("PHONENUMBER_DEFAULT_FORMAT")
PHONENUMBER_DEFAULT_REGION = env("PHONENUMBER_DEFAULT_REGION")
